on:
  workflow_call:
    inputs:
      protocol_name:
        required: true
        type: string
      package_name:
        required: true
        type: string

name: Build

jobs:
  build:
    strategy:
      matrix:
        platform: [linux-x86_64, macos-x86_64]
        include:
          - platform: linux-x86_64
            ci_image: ubuntu-20.04
            cargo_target: x86_64-unknown-linux-gnu
            sed_command: sed
          - platform: macos-x86_64
            ci_image: macos-12
            cargo_target: x86_64-apple-darwin
            sed_command: gsed
    runs-on: ${{ matrix.ci_image }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release --target ${{ matrix.cargo_target }}
      - name: Install sed
        if: ${{ startsWith(matrix.ci_image, 'macos') }}
        run: brew install gnu-sed
      - name: Pack
        run: |
          ${{ matrix.sed_command }} -i '/^entrypoint =/centrypoint = "./${{ inputs.package_name }}"' colink.toml
          cp target/${{ matrix.cargo_target }}/release/${{ inputs.package_name }} ./
          tar -zcvf ${{ inputs.package_name }}-${{ matrix.platform }}.tar.gz ${{ inputs.package_name }} colink.toml
      - name: Upload Release Asset
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }},
              name: '${{ inputs.package_name }}-${{ matrix.platform }}.tar.gz',
              data: await fs.readFile('${{ inputs.package_name }}-${{ matrix.platform }}.tar.gz')
            });

  update-inventory:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Commit Hash
        id: commit_hash
        run: echo "commit_hash=`git rev-parse HEAD`" >> $GITHUB_OUTPUT
      - name: Sha256
        id: sha256
        run: |
          export platform=linux-x86_64
          wget ${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ inputs.package_name }}-$platform.tar.gz
          echo "sha256-$platform=`shasum -a 256 ${{ inputs.package_name }}-$platform.tar.gz | awk '{ print $1 }'`" >> $GITHUB_OUTPUT
          export platform=macos-x86_64
          wget ${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ inputs.package_name }}-$platform.tar.gz
          echo "sha256-$platform=`shasum -a 256 ${{ inputs.package_name }}-$platform.tar.gz | awk '{ print $1 }'`" >> $GITHUB_OUTPUT
      - name: Generate
        run: |
          cp inventory-template.toml ${{ inputs.protocol_name }}.toml
          sed -i 's#{{source.git.url}}#${{ github.event.repository.clone_url }}#' ${{ inputs.protocol_name }}.toml
          sed -i 's#{{source.git.commit}}#${{ steps.commit_hash.outputs.commit_hash }}#' ${{ inputs.protocol_name }}.toml
          sed -i 's#{{binary.linux-x86_64.url}}#${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ inputs.package_name }}-linux-x86_64.tar.gz#' ${{ inputs.protocol_name }}.toml
          sed -i 's#{{binary.linux-x86_64.sha256}}#${{ steps.sha256.outputs.sha256-linux-x86_64 }}#' ${{ inputs.protocol_name }}.toml
          sed -i 's#{{binary.macos-x86_64.url}}#${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ inputs.package_name }}-macos-x86_64.tar.gz#' ${{ inputs.protocol_name }}.toml
          sed -i 's#{{binary.macos-x86_64.sha256}}#${{ steps.sha256.outputs.sha256-macos-x86_64 }}#' ${{ inputs.protocol_name }}.toml
      - name: SSH Agent
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Clone inventory repository
        run: git clone git@github.com:CoLearn-Dev/colink-protocol-inventory.git
      - name: Copy
        run: cp ${{ inputs.protocol_name }}.toml colink-protocol-inventory/protocols/
      - name: Set pusher
        run: |
          git config --global user.email "104302037+colearn-dev-bot@users.noreply.github.com"
          git config --global user.name "colearn-dev-bot"
      - name: Add
        working-directory: ./colink-protocol-inventory
        run: git add protocols/${{ inputs.protocol_name }}.toml
      - name: Commit
        working-directory: ./colink-protocol-inventory
        run: git commit -m "Update ${{ inputs.protocol_name }}"
      - name: Push
        working-directory: ./colink-protocol-inventory
        run: git push
